name = "ABCConformal"
uuid = "6a06312b-1f35-42d8-b2e0-a51b61531d54"
authors = ["David Métivier <david.metivier@inrae.fr>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
